INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'you have won', 1.0, 'lottery', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'you have been selected', 1.0, 'lottery', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'congratulations you won', 1.0, 'lottery', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'claim your prize', 1.0, 'lottery', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'claim your reward', 0.9, 'lottery', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'you are a winner', 1.0, 'lottery', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'lucky winner', 0.9, 'lottery', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'selected as winner', 1.0, 'lottery', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'awarded a prize', 0.9, 'lottery', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'free gift', 0.7, 'lottery', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'gift voucher', 0.6, 'lottery', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'scratch and win', 0.8, 'lottery', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'spin to win', 0.8, 'lottery', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'cash prize', 0.8, 'lottery', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'jackpot winner', 0.9, 'lottery', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'grand prize', 0.8, 'lottery', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'mpesa pin', 1.0, 'kenya_mobile_money', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'send your pin', 1.0, 'kenya_mobile_money', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'share your pin', 1.0, 'kenya_mobile_money', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'enter your pin', 0.9, 'kenya_mobile_money', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'confirm your pin', 0.9, 'kenya_mobile_money', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'mpesa reversal', 0.9, 'kenya_mobile_money', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'sent money by mistake', 0.9, 'kenya_mobile_money', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'reverse the transaction', 0.8, 'kenya_mobile_money', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'safaricom account suspended', 1.0, 'kenya_mobile_money', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'safaricom verification', 0.9, 'kenya_mobile_money', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'safaricom customer care', 0.7, 'kenya_mobile_money', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'mpesa account blocked', 1.0, 'kenya_mobile_money', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'mpesa account suspended', 1.0, 'kenya_mobile_money', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'update your mpesa', 0.9, 'kenya_mobile_money', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'airtel money pin', 1.0, 'kenya_mobile_money', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'tkash pin', 1.0, 'kenya_mobile_money', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'fuliza limit', 0.7, 'kenya_mobile_money', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'lipa na mpesa', 0.5, 'kenya_mobile_money', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'paybill number', 0.5, 'kenya_mobile_money', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'till number', 0.4, 'kenya_mobile_money', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'kcb account blocked', 1.0, 'kenya_bank', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'kcb account suspended', 1.0, 'kenya_bank', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'equity bank verification', 0.9, 'kenya_bank', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'equity account blocked', 1.0, 'kenya_bank', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'cooperative bank', 0.5, 'kenya_bank', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'absa bank alert', 0.7, 'kenya_bank', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'stanchart verification', 0.8, 'kenya_bank', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'dtb bank', 0.5, 'kenya_bank', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'i&m bank alert', 0.7, 'kenya_bank', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'family bank alert', 0.7, 'kenya_bank', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'verify your bank account', 0.9, 'kenya_bank', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'bank account deactivated', 0.9, 'kenya_bank', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'bank account suspended', 0.9, 'kenya_bank', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'unusual activity detected', 0.8, 'kenya_bank', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'suspicious transaction', 0.7, 'kenya_bank', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'send otp', 1.0, 'otp_phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'share otp', 1.0, 'otp_phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'your otp is', 0.8, 'otp_phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'one time password', 0.7, 'otp_phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'verification code', 0.6, 'otp_phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'security code', 0.6, 'otp_phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'do not share this code', 0.8, 'otp_phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'never share your code', 0.8, 'otp_phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'enter verification code', 0.7, 'otp_phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'confirm your identity', 0.7, 'otp_phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'verify your account', 0.8, 'phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'account verification required', 0.8, 'phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'your account will be deactivated', 0.9, 'phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'account expires', 0.8, 'phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'update your details', 0.7, 'phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'update your information', 0.7, 'phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'login immediately', 0.8, 'phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'click here to verify', 0.8, 'phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'click here to activate', 0.8, 'phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'click here immediately', 0.8, 'phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'confirm your account', 0.7, 'phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'your account has been locked', 0.9, 'phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'your account has been compromised', 0.9, 'phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'unauthorised login attempt', 0.8, 'phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'password reset required', 0.6, 'phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'apple id suspended', 0.9, 'phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'google account suspended', 0.9, 'phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'microsoft account blocked', 0.9, 'phishing', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'nigerian prince', 1.0, 'advance_fee', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'inheritance funds', 0.9, 'advance_fee', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'inheritance transfer', 0.9, 'advance_fee', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'funds transfer', 0.7, 'advance_fee', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'confidential transaction', 0.9, 'advance_fee', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'business proposal', 0.5, 'advance_fee', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'million dollars', 0.8, 'advance_fee', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'million usd', 0.8, 'advance_fee', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'unclaimed funds', 0.9, 'advance_fee', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'dormant account', 0.7, 'advance_fee', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'next of kin', 0.7, 'advance_fee', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'deceased customer', 0.8, 'advance_fee', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'share the funds', 0.9, 'advance_fee', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'transfer the money', 0.7, 'advance_fee', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'keep this confidential', 0.8, 'advance_fee', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'send money', 0.7, 'financial_fraud', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'wire transfer', 0.8, 'financial_fraud', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'western union', 0.8, 'financial_fraud', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'money gram', 0.8, 'financial_fraud', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'free money', 1.0, 'financial_fraud', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'make money fast', 0.9, 'financial_fraud', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'earn from home', 0.7, 'financial_fraud', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'work from home', 0.4, 'financial_fraud', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'no investment required', 0.8, 'financial_fraud', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'double your money', 1.0, 'financial_fraud', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'guaranteed returns', 0.9, 'financial_fraud', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), '100% guaranteed', 0.8, 'financial_fraud', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'risk free investment', 0.9, 'financial_fraud', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'forex trading profit', 0.7, 'financial_fraud', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'investment opportunity', 0.5, 'financial_fraud', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'loan approved', 0.6, 'financial_fraud', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'instant loan', 0.6, 'financial_fraud', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'no credit check', 0.7, 'financial_fraud', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'debt relief', 0.5, 'financial_fraud', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'bitcoin payment', 0.9, 'crypto', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'bitcoin wallet', 0.8, 'crypto', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'send bitcoin', 0.9, 'crypto', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'cryptocurrency investment', 0.7, 'crypto', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'crypto wallet', 0.7, 'crypto', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'binance account', 0.6, 'crypto', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'ethereum transfer', 0.8, 'crypto', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'nft investment', 0.7, 'crypto', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'crypto mining', 0.6, 'crypto', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'blockchain reward', 0.8, 'crypto', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'gift card', 0.8, 'gift_card', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'itunes gift card', 0.9, 'gift_card', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'google play card', 0.9, 'gift_card', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'amazon gift card', 0.9, 'gift_card', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'steam gift card', 0.9, 'gift_card', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'buy gift cards', 0.9, 'gift_card', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'send gift card', 0.9, 'gift_card', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'gift card code', 0.9, 'gift_card', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'scratch card number', 0.9, 'gift_card', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'act now', 0.6, 'urgency', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'limited time', 0.5, 'urgency', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'expires today', 0.7, 'urgency', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'expires in 24 hours', 0.7, 'urgency', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'respond immediately', 0.7, 'urgency', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'urgent action required', 0.8, 'urgency', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'immediate action', 0.7, 'urgency', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'last chance', 0.6, 'urgency', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'do not ignore', 0.7, 'urgency', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'final warning', 0.8, 'urgency', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'final notice', 0.8, 'urgency', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'account will be closed', 0.8, 'urgency', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'respond within 24 hours', 0.7, 'urgency', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'respond within 48 hours', 0.6, 'urgency', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'job offer', 0.4, 'job_scam', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'you have been hired', 0.8, 'job_scam', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'work from home opportunity', 0.7, 'job_scam', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'part time job', 0.4, 'job_scam', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'earn ksh daily', 0.9, 'job_scam', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'earn usd daily', 0.9, 'job_scam', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'data entry job', 0.5, 'job_scam', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'no experience required', 0.6, 'job_scam', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'high salary', 0.4, 'job_scam', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'payment upfront', 0.8, 'job_scam', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'training fee', 0.8, 'job_scam', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'registration fee', 0.7, 'job_scam', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'i love you', 0.2, 'romance', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'send me money', 0.9, 'romance', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'stuck in hospital', 0.8, 'romance', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'stranded abroad', 0.8, 'romance', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'need emergency funds', 0.8, 'romance', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'plane ticket', 0.5, 'romance', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'military deployment', 0.6, 'romance', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'visa fees', 0.7, 'romance', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'kenya revenue authority', 0.6, 'govt_impersonation', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'kra tax refund', 0.9, 'govt_impersonation', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'tax refund', 0.8, 'govt_impersonation', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'government grant', 0.8, 'govt_impersonation', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'covid relief funds', 0.9, 'govt_impersonation', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'nhif suspended', 0.9, 'govt_impersonation', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'nssf account', 0.6, 'govt_impersonation', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'huduma number', 0.6, 'govt_impersonation', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'police clearance', 0.5, 'govt_impersonation', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'immigration alert', 0.7, 'govt_impersonation', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'passport suspended', 0.9, 'govt_impersonation', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'arrest warrant', 0.9, 'govt_impersonation', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'court summons', 0.8, 'govt_impersonation', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'fine payment', 0.6, 'govt_impersonation', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'your device is infected', 0.9, 'tech_support', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'virus detected', 0.8, 'tech_support', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'call microsoft', 0.9, 'tech_support', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'call apple support', 0.9, 'tech_support', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'remote access', 0.7, 'tech_support', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'download this app', 0.6, 'tech_support', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'install this software', 0.6, 'tech_support', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'technical support', 0.4, 'tech_support', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'your computer has been hacked', 0.9, 'tech_support', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'free trial', 0.4, 'subscription', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'cancel anytime', 0.3, 'subscription', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'billed monthly', 0.3, 'subscription', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'auto renewal', 0.4, 'subscription', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'unsubscribe', 0.3, 'subscription', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'premium membership', 0.5, 'subscription', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'vip access', 0.6, 'subscription', 1);
INSERT IGNORE INTO banned_keywords (keyword_id, keyword, weight, category, is_active) VALUES (UUID(), 'exclusive membership', 0.5, 'subscription', 1);